name: Test Bun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest
      - run: bun install
      - run: bun ./print.ts
